### PR TITLE
Change scope of compile options to PRIVATE

### PR DESCRIPTION
**Pull request by gunnarhelgason**
Currently the compiler options for pcsc-cpp are added with a PUBLIC scope. This means that the options also will be used when compiling projects that depend on and build pcsc-cpp as part of their build. This imposes compiler options on client code that might not be desired, e.g. -Werror.

This PR changes the scope to PRIVATE.

### CODE REVIEW

**Comment by mrts** [comment]
Thank you for the suggestion! We intend to implement a bit more complex solution by using interface pseudo-libraries for compiler options (see the  `enable_rtti` example in https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#interface-libraries).

**Comment by mrts** [comment]
@gunnarhelgason, would you be interested in contributing a patch that moves the compiler options to a interface pseudo-library? (Like the `enable_rtti` example in https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#interface-libraries).

**Comment by gunnarhelgason** [comment]
@mrts, apologies for the late response. I would like to help, but I'm not sure I understand the motivation for moving the compiler options to an interface pseudo-library. If I understand correctly, using INTERFACE scope for target_compile_options will apply the options to compilation of the client/consumer code. Could you explain why this is needed? As far as I understand, it would not solve my original issue, which mainly was that my code was compiled with -Werror due to the PUBLIC scope in the pcsc-cpp CMake file.

My CMake experience is limited (to put it mildly.. :smile: ), so please let me know if I have misunderstood something.

**Comment by kristelmerilain** [comment]
Thank You for the contribution!
Please note that the libpcsc-cpp code was moved to libelectronic-id repository.
We are happy to accept your proposals in the libelectronic-id repository: https://github.com/web-eid/libelectronic-id.
We won't be accepting pull requests or responding to issues in this repository anymore.

**Pull request closed without merging**
